CREATE TABLE IF NOT EXISTS telegram_tasks
(
    `id`         INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `request`    TEXT NOT NULL,
    `response`   TEXT      DEFAULT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
